//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string User { get; set; }
        public string Pass { get; set; }
        public string HoTen { get; set; }
    }
}
