//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDatTourEntities : DbContext
    {
        public QLDatTourEntities()
            : base("name=QLDatTourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chuyen> Chuyens { get; set; }
        public DbSet<DiaDiemThamQuan> DiaDiemThamQuans { get; set; }
        public DbSet<DungChan> DungChans { get; set; }
        public DbSet<HangKhachSan> HangKhachSans { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<HuongDanVien> HuongDanViens { get; set; }
        public DbSet<KhachLe> KhachLes { get; set; }
        public DbSet<KhachSan> KhachSans { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhieuDoan> PhieuDoans { get; set; }
        public DbSet<PhuongTien> PhuongTiens { get; set; }
        public DbSet<ThanhVien> ThanhViens { get; set; }
        public DbSet<Tour> Tours { get; set; }
        public DbSet<Admin> Admins { get; set; }
    }
}
