//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaDiemThamQuan
    {
        public DiaDiemThamQuan()
        {
            this.DungChans = new HashSet<DungChan>();
        }
    
        public string MaThamQuan { get; set; }
        public string TenDiaDiem { get; set; }
        public string NoiDung { get; set; }
        public string AnhDiaDiem { get; set; }
        public string YNghia { get; set; }
    
        public virtual ICollection<DungChan> DungChans { get; set; }
    }
}
