//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DungChan
    {
        public string MaThamQuan { get; set; }
        public string MaTour { get; set; }
        public string MaPT { get; set; }
    
        public virtual DiaDiemThamQuan DiaDiemThamQuan { get; set; }
        public virtual PhuongTien PhuongTien { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
