//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangKhachSan
    {
        public HangKhachSan()
        {
            this.KhachSans = new HashSet<KhachSan>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
    
        public virtual ICollection<KhachSan> KhachSans { get; set; }
    }
}
