//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.Chuyens = new HashSet<Chuyen>();
        }
    
        public string MaHoaDon { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<double> ConLai { get; set; }
        public Nullable<double> TienDatCoc { get; set; }
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public string MaKhachLe { get; set; }
    
        public virtual KhachLe KhachLe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuyen> Chuyens { get; set; }
    }
}
