//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDoan
    {
        public PhieuDoan()
        {
            this.ThanhViens = new HashSet<ThanhVien>();
            this.HuongDanViens = new HashSet<HuongDanVien>();
        }
    
        public string MaDoan { get; set; }
        public string TenCQ { get; set; }
        public string DiaChiCQ { get; set; }
        public string SDTCQ { get; set; }
        public string TenNĐD { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<byte> SoNguoi { get; set; }
        public string MaTour { get; set; }
        public string MaNV { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual ICollection<ThanhVien> ThanhViens { get; set; }
        public virtual ICollection<HuongDanVien> HuongDanViens { get; set; }
    }
}
