//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOUR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        public string STT { get; set; }
        public string CMNDTV { get; set; }
        public string DiaChiTV { get; set; }
        public string SDTTV1 { get; set; }
        public string SDTTV2 { get; set; }
        public string HoTenTV { get; set; }
        public string MaDoan { get; set; }
    
        public virtual PhieuDoan PhieuDoan { get; set; }
    }
}
